# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
    command_interfaces:
      []
    state_interfaces:
      []
gripper_controller:
  ros__parameters:
    joint: gripper_joint