controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController
    

diff_cont:
  ros__parameters:

    publish_rate:   50.0

    base_frame_id: base_link

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.56
    wheel_radius: 0.08

    use_stamped_vel: false

    # wheel_separation_multiplier: 1.0
    # left_wheel_radius_multiplier: 1.0
    # right_wheel_radius_multiplier: 1.0

    # odom_frame_id: odom
    # pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # position_feedback: false
    # open_loop: true
    # enable_odom_tf: true

    # cmd_vel_timeout: 0.5 # seconds
    # publish_limited_velocity: true
    # velocity_rolling_window_size: 10

    # linear.x.max_velocity: .NAN
    # linear.x.min_velocity: .NAN
    # linear.x.max_acceleration: .NAN
    # linear.x.max_deceleration: .NAN
    # linear.x.max_acceleration_reverse: .NAN
    # linear.x.max_deceleration_reverse: .NAN
    # linear.x.max_jerk: .NAN
    # linear.x.min_jerk: .NAN

    # angular.z.max_velocity: .NAN
    # angular.z.min_velocity: .NAN
    # angular.z.max_acceleration: .NAN
    # angular.z.max_deceleration: .NAN
    # angular.z.max_acceleration_reverse: .NAN
    # angular.z.max_deceleration_reverse: .NAN
    # angular.z.max_jerk: .NAN
    # angular.z.min_jerk: .NAN


arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joint_goals: false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0


gripper_controller:
  ros__parameters:
    joint: gripper_joint
    
    action_monitor_rate: 20.0